---

- name: Test playbook - reads and prints device info
  hosts: homekit
  gather_facts: false
  connection: network_cli
  roles:
  - common

  tasks:

    - name: Run "show version" command on devices
      ios_command:
        commands: show version
      register: output

    - name: Print the output of "show version"
      debug:
        var: output.stdout_lines