---
- name: Update and upgrade packages on Raspberries
  hosts: all
  roles:
    - common
  remote_user: vlad
  become: yes
  vars:
    run: false
    reboot: false

  tasks:

      - name: Update package repositories
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Upgrade packages on targets
        apt: upgrade=dist force_apt_get=yes 

      - name: Get uptime information
        shell: "/usr/bin/uptime"
        register: my_uptime
        
      - name: Print uptime information
        debug: 
          var: my_uptime.stdout
          verbosity: 0

      - name: Get interface configuration
        shell: "ifconfig"
        register: my_interfaces

      - name: Print MOTD information
        debug: 
          var: my_interfaces.stdout_lines
          verbosity: 0

